version: '3.1'

services:

  db:
    container_name: dse-db
    image: mongo
    restart: always
    hostname: db
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./data/mongo:/data/db
    expose:
      - 27017
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=YDch0mFpr27R


  api:
    container_name: dse-api
    image: "registry.gitlab.utwente.nl/bmslabexternal/dse:api-devserver"
    restart: always
    ports:
      - "5004:5004"
    environment:
      - "DB_HOST=db"
      - "DB_PORT=27017"
      - "DB_USER=root"
      - "DB_PASS=YDch0mFpr27R"
      - "DB_NAME=dse"
      - "WS_TOKEN=110152"
      - "WS_HOST=0.0.0.0"
      - "WS_PORT=5004"
      - "SMTP_USER=digitalepolarisatie.nl"
      - "SMTP_HOST=info@digitalepolarisatie.nl"
      - "SMTP_PASS=34dVi%s4"